config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  resources :products
  resources :categories
  devise_for :users
  root to: 'products#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  before_destroy :not_referenced_by_any_line_item
  mount_uploader :image, ImageUploader
  belongs_to :category
  has_one_attached :product_image
  has_many :line_items
  # validate :name, :price, :quantity, presence: true

  private

  def not_referenced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, "Line items present")
      throw :abort
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except:  [:index, :show]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    @categories = Category.all
  end

  # GET /products/1/edit
  def edit
    @categories = Category.all
  end

  # POST /products
  # POST /products.json
  def create
    
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      if LineItem.find_by_product_id @product.id
        format.html { redirect_to products_url, notice: 'Can not delete a product that has already been ordered.' }
        format.json { head :no_content }
      else        
        format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
        format.json { head :no_content }
      end    
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :quantity, :description, :category_id, :product_image)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
    def admin?
        current_user && current_user.admin
    end
end

app/views/products/_form.html.erb
<div class="container">
  <div class="columns">
    <div class="column is-8 is-centered">
    
      <%= simple_form_for @product, html: { multipart: true } do |f| %>
        <%= f.error_notification %>

          <div class="columns">

            <div class="field column is-9">
              <div class="control">
                <%= f.input :name , required: true, input_html: { class: "input"}, wrapper: false, label_html: { class:"label" } %>
              </div>
            </div>

            <div class="field column">
              <div class="control">
                <%= f.input :price, required: true, input_html: { class:"input", maxlength: 7  }, wrapper: false, label_html: { class:"label" } %>
              </div>
            </div>

          </div>

          <div class="field">
            <div class="control">
              <%= f.input :quantity, required: true, input_html: { class:"input" }, wrapper: false, label_html: { class:"label" } %>
            </div>
          </div>

          <div class="field">
            <div class="control">
              <%= f.input :description, required: true, input_html: { class:"textarea" }, wrapper: false, label_html: { class:"label" } %>
            </div>
          </div>

          <div class="columns">
            <div class="field column">
              <div class="control">
                <label class="label">Category</label>
                <div class="control has-icons-left">
                  <span class="select">
                    <%= f.collection_select(:category_id, categories, :id, :title) %>
                  </span>
                  <span class="icon is-small is-left">
                    <i class="fa fa-tag"></i>
                  </span>
                </div>
              </div>
            </div>
            </div>

          <div class="field">
            <div class="control">
              <label class="label">Add image</label>
                <div class="file">
                <label class="file-label">
                    <span class="file-cta">
                      <span class="file-icon"><i class="fa fa-upload"></i></span>
                      <span class="file-label"><%= f.file_field :product_image %><br></span>
                    </span>
                </label>
                </div>
              </div>
            </div>
            <output id="list"></output>
          <hr />

          <div class="field is-grouped">
            <div class="control">
              <%= f.button :submit, class: 'button is-warning' %>
              <%= link_to 'Cancel', products_path, class:'button is-light' %>
            </div>
          </div>

        <% end %>
    </div>
  </div>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product, categories: @categories %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<% if admin? %>
  <%= link_to 'Create New Product', new_product_path %>
<% end %>

<% content_for :header do %>
  <section class="hero is-warning">
    <div class="hero-body">
      <div class="container">
        <h1 class="title">
          Buy products from us
        </h1>
      </div>
    </div>
  </section>
  <% end %>
  
  <div class="instrument-index-grid pt4">
    <% @products.each do |product| %>
  
      <div class="instrument border-light">
        <div class="instrument-thumb">
        <%= link_to image_tag(url_for(product.product_image)), product %>
        </div>
  
  
      <div class="pa3">
  
        <h3 class="fw7 f4 title"><%= link_to product.name, product %></h3>
  
        <p class="f3 fw6 has-text-right pt2 price"><%= number_to_currency(product.price) %></p>
  
        <% if admin? %>
          <%= link_to 'Edit', edit_product_path(product), class: "button is-small" %>
          <%= link_to 'Delete', product, method: :delete, data: { confirm: 'Are you sure?' } , class: "button is-small" %>
        <% end %>
        <%= link_to 'Show', product, class: "button is-small" %>
      </div>
    </div>
    <% end %>
  </div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product, categories: @categories %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<%= link_to 'Back', products_path %>

<% content_for :body_class, 'bg-light' %>

<section class="section instrument-show">
  <div class="columns">
    <div class="column is-8">
      <h1 class="title is-2"><%= @product.name %></h1>

      <div class="feature-image">
        <%= image_tag(url_for(@product.product_image)) %>
      </div>

      <div class="content pa4 mt3 bg-white border-radius-3">

      <h3 class="subtitle is-4">Description</h3>
      <%= @product.description %>
    </div>
    </div>
    <div class="column is-3 is-offset-1">
      <div class="bg-white pa4 border-radius-3">
        <h4 class="title is-5 has-text-centered"><%= number_to_currency(@product.price) %></h4>
        <p class="has-text-centered mb4">Available <%= @product.quantity %></p>
        <%= button_to 'Add to cart', line_items_path(product_id: @product), class: 'button is-warning add-to-cart' %>
      </div>
    </div>
  </div>

  <% if admin? %>
    <%= link_to 'Edit', edit_product_path(@product), class: 'button' %>
  <% end %>
</section>